apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-nginx
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}-nginx
        app.kubernetes.io/part-of: {{ include "name" . }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: {{ include "name" . }}-pvc-cache
      containers:
        - name: {{ .Chart.Name }}-nginx
          volumeMounts:
            - mountPath: /srv/api/public/media/cache
              name: image-cache
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: cors-allow-origin
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
