apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-php
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-php
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}-php
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
      volumes:
        - name: php-uploads
          persistentVolumeClaim:
            claimName: {{ include "name" . }}-pvc-uploads
        - name: image-cache
          persistentVolumeClaim:
            claimName: {{ include "name" . }}-pvc-cache
      containers:
        - name: {{ .Chart.Name }}-php
          volumeMounts:
          - mountPath: /srv/api/var/uploads
            name: php-uploads
          - mountPath: /srv/api/public/media/cache
            name: image-cache
          image: "{{ .Values.php.repository }}:{{ .Values.php.tag }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: debug
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: cors-allow-origin
            - name: VARNISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: varnish-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-url
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: jwt-secret-key
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: jwt-public-key
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: jwt-passphrase
            - name: PASSWORD_MANAGER_TOKEN_TTL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: password-manager-token-ttl
            - name: PASSWORD_REQUEST_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: password-request-timeout
            - name: MAILER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mailer-dsn
            - name: VARNISH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: varnish-token
            - name: COOKIE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie-domain
            - name: FROM_EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: from-email-address

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
