kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "api.fullname" . }}-pvc-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size.uploads }}
