apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  database-url: {{ .Values.mysql.url | b64enc | quote }}
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  jwt-secret-key: {{ .Values.php.jwt.secretKey | b64enc | quote }}
  jwt-public-key: {{ .Values.php.jwt.publicKey | b64enc | quote }}
  jwt-passphrase: {{ .Values.php.jwt.passphrase | b64enc | quote }}
  varnish-token: {{ .Values.php.varnishToken | b64enc | quote }}