apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-smtp-relay
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-smtp-relay
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}-smtp-relay
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-smtp-relay
          image: "namshi/smtp:latest"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 25
          env:
            - name: RELAY_NETWORKS
              value: ':192.168.1.0/24'
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
