apiVersion: v1
kind: Service
metadata:
    name: smtp-relay
    labels:
        app.kubernetes.io/name: {{ include "name" . }}-smtp-relay
        app.kubernetes.io/part-of: {{ include "name" . }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: ClusterIP
    ports:
        - port: 25
    selector:
        app.kubernetes.io/name: {{ include "name" . }}-smtp-relay
        app.kubernetes.io/instance: {{ .Release.Name }}
