version: '3.6'

services:
    mysql:
        image: mysql
        volumes:
            - db-mysql:/var/lib/mysql:rw
        env_file:
            - ./shared/.env
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"

    php:
        build:
            context: ./api
            dockerfile: ./_docker/php/Dockerfile
        depends_on:
            - mysql
        env_file:
            - ./shared/.env
            - ./api/.env
        restart: on-failure

    app:
        build:
            context: ./app
            dockerfile: ./_docker/Dockerfile
        env_file:
            - ./shared/.env
            - ./app/.env

    nginx:
        build:
            context: ./api
            dockerfile: ./_docker/nginx/Dockerfile
        depends_on:
            - php

    varnish:
        build:
            context: ./api
            dockerfile: ./_docker/varnish/Dockerfile
        depends_on:
            - nginx

volumes:
    db-mysql:
