version: '3'

services:
#    varnish:
#        environment:
#            HTTPS_METHOD: noredirect
#            VIRTUAL_HOST: api.starter.b-w.uk
#            LETSENCRYPT_HOST: api.starter.b-w.uk
#            LETSENCRYPT_EMAIL: info@silverbackhosting.com
#            VIRTUAL_PORT: 80
#        expose:
#            - 80
#        networks:
#            - default
#            - proxy

    nginx:
        environment:
            HTTPS_METHOD: noredirect
            VIRTUAL_HOST: api.starter.b-w.uk
            LETSENCRYPT_HOST: api.starter.b-w.uk
            LETSENCRYPT_EMAIL: info@silverbackhosting.com
            VIRTUAL_PORT: 80
        expose:
            - 80
        networks:
            - default
            - proxy

    app:
        environment:
            HTTPS_METHOD: noredirect
            VIRTUAL_HOST: starter.b-w.uk
            LETSENCRYPT_HOST: starter.b-w.uk
            LETSENCRYPT_EMAIL: info@silverbackhosting.com
            VIRTUAL_PORT: 3000
        expose:
            - 3000
        networks:
            - default
            - proxy

networks:
  proxy:
    external:
      name: proxy
