version: '3.7'

x-cache:
  &cache
    cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
        - ${CONTAINER_REGISTRY_BASE}/app

services:
    php:
        image: ${CONTAINER_REGISTRY_BASE}/php
        build:
            context: ./api
            target: sbwa_php
            <<: *cache
        depends_on:
            - db
        environment:
            XDEBUG_HOST: ${XDEBUG_HOST}
        networks:
            - blackfire
            - smtp
            - api

    nginx:
        image: ${CONTAINER_REGISTRY_BASE}/nginx
        build:
            context: ./api
            target: sbwa_nginx
            <<: *cache
        depends_on:
            - php
        networks:
            - api

    varnish:
        image: ${CONTAINER_REGISTRY_BASE}/varnish
        build:
            context: ./api
            target: sbwa_varnish
            <<: *cache
        depends_on:
            - nginx
        tmpfs:
            - /usr/local/var/varnish:exec
        networks:
            - api
            - app

    smtp_relay:
        image: namshi/smtp
        networks:
            - smtp

    blackfire:
        image: blackfire/blackfire
        env_file:
            - ./api/_docker/blackfire/.env
        networks:
            - blackfire

    db:
        # for mysql v8 we would want PR merged here for node https://github.com/mysqljs/mysql/pull/1962 + release
        image: mysql:5
        networks:
            - api
            - app

    app:
        image: ${CONTAINER_REGISTRY_BASE}/app
        build:
            context: ./app
            target: sbwa_app
            <<: *cache
        depends_on:
            - db
        networks:
            - app
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 250M
                reservations:
                    cpus: '0.5'
                    memory: 100M

networks:
    app:
    api:
    blackfire:
    smtp:
