version: '3'

services:
    mysql:
        ports:
            - "4306:3306"
    php:
        volumes:
            - /srv/api/var/
            - /srv/api/var/cache/
            - /srv/api/var/sessions/
    api:
        ports:
            - "8080:80"
    varnish:
        volumes:
            - ./api/_docker/varnish/conf:/etc/varnish:ro
        ports:
            - "8081:80"
    app:
        ports:
            - "80:3000"
