version: '3'

services:
    mysql:
        ports:
            - "4306:3306"
    php:
        volumes:
            - /srv/api/var/
            - /srv/api/var/cache/
            - /srv/api/var/logs/
            - /srv/api/var/sessions/
    nginx:
        ports:
            - "8080:80"
    varnish:
        ports:
            - "8081:80"
    app:
        ports:
            - "80:3000"
