version: '3.7'

services:
    php:
        volumes:
            - api-public:/srv/api/public:rw,cached
            - api-uploads:/srv/api/var/uploads:rw,cached
            - jwt-keys:/srv/api/config/jwt
        env_file:
            - ./shared/.env.prod.local
            - ./api/.env.prod.local

    nginx:
        volumes:
            - api-public:/srv/api/public:ro,cached
        env_file:
            - ./shared/.env.prod.local

    varnish:
        networks:
            - traefik_traefik
        labels:
            - "traefik.enable=true"
            - "traefik.api.port=80"
            - "traefik.api.protocol=http"
            - "traefik.api.frontend.rule=Host:${API_HOST}"

    db:
        volumes:
            - mysql-data:/var/lib/mysql:rw,delegated
        env_file:
            - ./shared/.env.prod.local

    app:
        networks:
            - traefik_traefik
        env_file:
            - ./shared/.env.prod.local
            - ./app/_docker/.env.prod.local
        labels:
            - "traefik.enable=true"
            - "traefik.app.frontend.rule=Host:${APP_HOST}"
            - "traefik.app.port=3000"
            - "traefik.app.protocol=http"

networks:
    traefik_traefik:
        external: true

volumes:
    api-public:
    mysql-data:
