version: '3.6'

services:
    mysql:
        ports:
            - "4306:3306"

    api:
        volumes:
            - ./api:/srv/api:rw
            # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
            # - ./api/var:/srv/api/var:rw
            # Uncomment this line to link in local composer packages (comment during composer updates)
            #- /Volumes/LaCie/GitHub/_BWStarter/api-component-bundle:/srv/api/vendor/silverbackis/api-component-bundle:ro

    nginx:
        volumes:
            - ./api/public:/srv/api/public:ro
        ports:
            - "8080:80"

    varnish:
        ports:
            - "8081:80"

    app:
        ports:
            - "80:3000"
        volumes:
            - ./app:/usr/src/app:rw
            # Uncomment this line to link in local node packages (comment during yarn upgrades)
            #- /Volumes/LaCie/GitHub/_BWStarter/node_modules/@bwstarter:/usr/src/app/node_modules/@bwstarter:ro
