version: '3'

services:
    mysql:
        env_file:
            - ./api/.env
        volumes:
            - ./docker/db/data:/var/lib/mysql:rw
    varnish:
        environment:
            VIRTUAL_HOST: api.starter.b-w.uk
            LETSENCRYPT_HOST: api.starter.b-w.uk
            LETSENCRYPT_EMAIL: info@silverbackhosting.com
        volumes:
            - ./api/_docker/varnish/conf:/etc/varnish:ro
            - ./:/usr/share/nginx/html:rw
        expose:
            - 80
    app:
        environment:
            VIRTUAL_HOST: starter.b-w.uk
            LETSENCRYPT_HOST: starter.b-w.uk
            LETSENCRYPT_EMAIL: info@silverbackhosting.com
        volumes:
            - ./app:/usr/src/app:rw
            - ./:/usr/share/nginx/html:rw
        expose:
            - 3000
        build:
            args:
                app_env: production

networks:
  default:
    external:
      name: nginx-proxy
