version: '3.7'

services:
    mysql:
        volumes:
            - mysql-data:/var/lib/mysql:rw,delegated
        env_file:
            - shared/.env.prod.local

    varnish:
        networks:
            - traefik_traefik
        labels:
            - "traefik.enable=true"
            - "traefik.api.port=80"
            - "traefik.api.protocol=http"
            - "traefik.api.frontend.rule=Host:${API_HOST}"

    app:
        env_file:
            - shared/.env.prod.local
            - app/_docker/.env.prod.local
        networks:
            - traefik_traefik
        labels:
            - "traefik.enable=true"
            - "traefik.app.port=3000"
            - "traefik.app.protocol=http"
            - "traefik.app.frontend.rule=Host:${APP_HOST},website.com,new.website.com"
            - "traefik.app.frontend.redirect.regex=^https?://(new.)?website.com(.*)$$"
            - "traefik.app.frontend.redirect.replacement=https://${APP_HOST}$$2"
            - "traefik.app.frontend.redirect.permanent=true"

    api:
        volumes:
            - api-public:/srv/api/public:rw,cached
            - api-uploads:/srv/api/var/uploads:rw
        env_file:
            - shared/.env.prod.local
            - api/.env.prod.local

    nginx:
        volumes:
            - api-public:/srv/api/public:ro,cached
        env_file:
            - shared/.env.prod.local

    admin:
        env_file:
            - ./admin/.env.prod.local
        networks:
            - traefik_traefik
        labels:
            - "traefik.enable=true"
            - "traefik.app.port=3000"
            - "traefik.app.protocol=http"
            - "traefik.app.frontend.rule=Host:admin.website.com"

networks:
    traefik_traefik:
        external: true

volumes:
    api-public:
    api-uploads:
    mysql-data:
