version: '3'

services:
    mysql:
        env_file:
            - ./api/.env
        volumes:
            - ./docker/db/data:/var/lib/mysql:rw
    varnish:
        environment:
            VIRTUAL_HOST: api.starter.b-w.uk
            LETSENCRYPT_HOST: api.starter.b-w.uk
            LETSENCRYPT_EMAIL: info@silverbackhosting.com
        expose:
            - 80
        networks:
          - proxy
          - default
        volumes:
            - ./:/usr/share/nginx/html
    app:
        environment:
            VIRTUAL_HOST: starter.b-w.uk
            LETSENCRYPT_HOST: starter.b-w.uk
            LETSENCRYPT_EMAIL: info@silverbackhosting.com
        expose:
            - 3000
        build:
            args:
                app_env: production
        networks:
          - proxy
        volumes:
            - ./:/usr/share/nginx/html

networks:
  proxy:
    external:
      name: proxy
