version: '3.7'

x-cache:
  &cache
    cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
        - ${CONTAINER_REGISTRY_BASE}/app

services:
    php:
        image: ${CONTAINER_REGISTRY_BASE}/php
        build:
            context: ./api
            target: sbwa_php
            <<: *cache
        depends_on:
            - db
        networks:
            - blackfire
            - smtp
            - api
        volumes:
            - ./api:/srv/api:rw,cached
        env_file:
            - ./shared/.env.local
            - ./api/.env.local
    nginx:
        image: ${CONTAINER_REGISTRY_BASE}/nginx
        build:
            context: ./api
            target: sbwa_nginx
            <<: *cache
        depends_on:
            - php
        networks:
            - api
        volumes:
            - ./api/public:/srv/api/public:ro
        ports:
            - "8080:80"
        env_file:
            - ./shared/.env.local

    varnish:
        image: ${CONTAINER_REGISTRY_BASE}/varnish
        build:
            context: ./api
            target: sbwa_varnish
            <<: *cache
        depends_on:
            - nginx
        tmpfs:
            - /usr/local/var/varnish:exec
        networks:
            - api
            - app
        volumes:
            - ./api/_docker/varnish/errors:/var/www/errors:ro
        ports:
            - "8081:80"
        env_file:
            - ./shared/.env.local

    smtp_relay:
        image: namshi/smtp
        networks:
            - smtp

    blackfire:
        image: blackfire/blackfire
        env_file:
            - ./api/_docker/blackfire/.env.local
        networks:
            - blackfire

    db:
        # for mysql v8 we would want PR merged here for node https://github.com/mysqljs/mysql/pull/1962 + release
        image: mysql:5
        networks:
            - api
            - app
        volumes:
            - mysql-data:/var/lib/mysql:rw,delegated
        ports:
            - "4306:3306"
        env_file:
            - ./shared/.env.local

    app:
        image: ${CONTAINER_REGISTRY_BASE}/app
        build:
            context: ./app
            target: sbwa_app
            <<: *cache
        depends_on:
            - db
        networks:
            - app
        ports:
            - "80:3000"
        volumes:
            - ./app:/usr/src/app:rw,delegated
        env_file:
            - ./shared/.env.local
            - ./app/_docker/.env.local

#    admin:
#        # Use a static website hosting service in production
#        # See https://facebook.github.io/create-react-app/docs/deployment
#        image: quay.io/api-platform/admin
#        build:
#            context: ./admin
#            cache_from:
#                - quay.io/api-platform/admin
#        volumes:
#            - ./admin:/usr/src/admin:rw,cached
#            - /usr/src/admin/node_modules
#        ports:
#            - "81:3000"
#        env_file:
#            - ./admin/.env.local

networks:
    app:
    api:
    blackfire:
    smtp:

volumes:
    mysql-data:
