api_platform:
    enable_swagger_ui: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform']
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json', '*/*']
        html:     ['text/html']
        text:     ['text/plain']
    patch_formats:
        json:     ['application/json'] # 'application/merge-patch+json',
        jsonapi:  ['application/vnd.api+json']
    title: 'Components Web App API'
    description: 'API for the front-end web application'
    version: 0.0.1-dev
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 10
        vary: ['Content-Type', 'Authorization']
        public: true
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: perPage