nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['POST', 'GET', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['content-type', 'authorization', 'access-control-request-method', 'access-control-request-headers', 'x-xsrf-token', 'cache-control', 'x-requested-with', 'cookie', 'if-none-match']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
