parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(MYSQL_HOST): ''
    env(MYSQL_USER): ''
    env(MYSQL_PASSWORD): ''
    env(MYSQL_DATABASE): ''
    env(DATABASE_URL): 'mysql://%env(MYSQL_USER)%:%env(MYSQL_PASSWORD)%@%env(MYSQL_HOST)%:3306/%env(MYSQL_DATABASE)%'

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '9'
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: /^(?!sessions)/
        types:
            citext: App\DoctrineExtension\DBAL\Types\Citext
        mapping_types:
            citext: citext
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
