liip_imagine:
    driver: "imagick"
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'
    enqueue: true
