silverback_api_component:
    table_prefix: ~
    mailer:
        logo_src: 'images/logo.svg'
        website_name: 'New CWA'
    user:
        class_name: App\Entity\User
        change_username_path: /account/confirm-username/{{ token }}/{{ email }}
