parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    #App\Form\Handler\:
    #    resource: '../src/Form/Handler/*'
    #    public: true

    #app.form_handler_service_locator:
    #    class: Symfony\Component\DependencyInjection\ServiceLocator
    #    tags: ['container.service_locator']
    #    arguments:
    #        -
    #            App\FooCommand: '@app.command_handler.foo'
    #            App\BarCommand: '@app.command_handler.bar'
